### ISSUE TITLE
Installation Instruction

### ISSUE THREAD

**Issue by pavanbhat1999** [rfaulhaber/sfdx-nix#1]
I have been trying to setup sfdx in nixos from a long time now.  Currently i have binary version of it.  Can you please explain the installation instructions for a beginner.

**Comment by rfaulhaber** [comment]
This is an attempt at packaging the Salesforce CLI as a [Nix flake](https://nixos.wiki/wiki/Flakes). If you already have a binary, or don't know how to use flakes, this repo won't be of much use to you. 

Since it's just a flake you can use it like any other flake, e.g. `nix run github:rfaulhaber/sfdx-nix` or what have you, or include it in any other flake, like:

```nix
inputs = {
  sfdx-nix.url = "github:rfaulhaber/sfdx-nix";
};

outputs = { sfdx-nix }: {
# whatever...
};
```

I haven't kept this repo up to date, as packaging the Salesforce CLI is exceptionally difficult because they use a lot of unconventional methods in their build process, so use at your own risk (to that end though, I'm hoping I can provide a more up-to-date version of this in the near future, and one that doesn't require `node2nix`).

**Comment by pavanbhat1999** [comment]
I have forked the project and updated it using node2nix I now have latest version. 
But It took long time to compule us8ng node2nix and does not seem like a good way. 

Waiting for any other way of packaging this..

**Comment by rfaulhaber** [comment]
Yeah I'm not thrilled with node2nix. Unfortunately in my experience there's not a lot of good options. 

Today I played around with just using a [regular old derivation](https://github.com/rfaulhaber/sfdx-nix/tree/use-derivation), but the resulting JavaScript doesn't run for reasons I can't figure out. Maybe one day!
