### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by xixiaofinland** [rfaulhaber/sfdx-nix#2]
Hi Ryan,

Thanks for creating this flake! It works like a charm.

I have a few questions:

1. Why did you change the name from `sf` to `salesforce-cli`? I couldn't find any obvious reason.
2. You've successfully transitioned from node2nix. Is the current solution significantly better?
3. As we can't `npm update` it, Will you keep this flake up-to-date when new Salesforce CLI versions are released? It's v2.39.1 while the latest ver is already 2.46.6
4. Are you keen to add it into nixpkgs?

Best regards,
Xi

**Comment by rfaulhaber** [comment]
Thanks for writing! Glad you like it.

1. At the time I thought this was a limitation of using flakes and I wasn't sure how to deal with it at the time. Your message has prompted me to fix this, so it should now be `sf`.  I want the package name to be `salesforce-cli`  ("`sf`" is an awfully generic name after all) but the executable should be `sf`. 
2. My concern with `node2nix` is that it hasn't been maintained in more than a year. Further, in the time since I created this flake, Salesforce has changed the build process for how the CLI tool is built, and `node2nix` was causing issues with the new build process (`node2nix` has some limitations with the types of dependencies it can fetch and cache, and `node2nix` struggled fetching a number of the necessary dependencies). My feeling is that the current solution is preferable since it doesn't rely on an unmaintained third-party code-generation tool, I can specify the package as a regular derivation, and I can build it as close as possible to how it's built outside of nix.
3. I'm hoping to keep it somewhat up to date. I just bumped the version now. Salesforce updates pretty frequently though so I can't guarantee it'll be constantly bleeding edge. PRs are welcome however!
4. I've been going back and forth on this point and I honestly haven't made up my mind. For one thing I didn't really consider this flake to be complete until recently. Also, the biggest concern with nixpkgs is that getting version bumps through takes a very long time, and given how frequently Salesforce updates this it might not be worth it.

**Comment by xixiaofinland** [comment]
Yeah, the new version is much more aligned!
![Image 011](https://github.com/rfaulhaber/sfdx-nix/assets/13655323/6ed5eec5-4d53-4731-a5ea-592be8f30c65)

I'm new to derivations (and to Nix as well). It looks like the build steps are a series of bash actions that carefully manage how to build the sf npm package. This approach is much more simpler/elegent without `node2nix` as an intermediary, especially since you've already figured out the build steps. Great work!

I'm happy to create PRs in the future to help update the versions. I also plan to spend some time studying how the derivation is structured.

If nixpkgs is a cumbersome process, then let's skip it. After all, I guess only dozens of ppl in this planet have the need of it :D

**Comment by rfaulhaber** [comment]
Haha yes exactly, I figure the venn diagram of nix users and Salesforce developers is just two circles. I'm not opposed to it though if there's enough of a demand. This could be pretty easily adapted into something that could be added to nixpkgs should the need arise.

**Comment by xixiaofinland** [comment]
Agreed! A side question, how do you handle `apex-jorje-lsp.jar` (the official apex lsp)? I currently download it into `~` @rfaulhaber

**Comment by rfaulhaber** [comment]
Let's take this offline. Shoot me an email and we can chat about it. I'll close this issue.
